### PR TITLE
Migrates to Scala 3

### PR DESCRIPTION
**Pull request by CJSmith-0141**
- Remove shapeless
- Remove refined
- Add `-Xsource:3` to scala 2.13 compiler flags
- Remove some arbitraries from the test suite

The idea behind this change is to get to scala 3. This unfortunately needed some removal of very nice compilation time checks, but gains scala 3.

### CODE REVIEW

**Comment by bpholt** [comment]
Thanks for this! We don't use Scala 3 much yet at Dwolla, but it's always nice to add support for it to our OSS libraries.

I think we can keep refined if we merge #190 (or something including it), because refined 0.11 has Scala 3 support (excluding the macros). It means we'd lose the compile-time refinements (unless we split them into Scala 2 and Scala 3 sources), but I'd rather just lose those than lose the refinement types altogether.

I have a branch locally where I've been playing with this (just to make sure it wasn't nonsense), so I'll push that up so you can take a look.

**Comment by CJSmith-0141** [comment]
Yeah I'll take a look at doing a PR that updates to `refined 0.11`, then rebase this PR after that one is merged.

**Comment by bpholt** [comment]
Sounds good, but FYI I have a couple other things staged locally that will cause merge issues; you may want to hold off for a bit to avoid rework (as much as possible)

**Comment by CJSmith-0141** [comment]
I'll hold off then. Thank you for taking a look at it 😄

**Comment by bpholt** [comment]
I proposed an alternative approach in #211.

**Pull request closed without merging**
