### PR TITLE
Adds bcprov-jdk18on as a direct dependency

### PR DESCRIPTION
**Pull request by CJSmith-0141**
I had an issue where I was explicitly importing `bcutil` of a previous Bouncy Castle version, and this was causing issues when trying to import `fs2-pgp:0.4.2` by itself. I found that adding the `bcprov` artifact back as a direct dependency fixed my issues, and figured you might want to do the same here.

### CODE REVIEW

**Comment by bpholt** [comment]
> this was causing issues when trying to import fs2-pgp:0.4.2 by itself

Can you elaborate what you meant here? What kind of issues?

To be honest, I was hoping not to have to track this, by letting the bcprov artifact be driven by the dependency specified in the bgpg POM file. (But maybe it's unavoidable, idk.)

**Comment by CJSmith-0141** [comment]
Looking at it again it looks like a problem with not having `bcutil` not `bcprov` being out-of-sync.
```
[info]   java.lang.NoSuchMethodError: 'java.math.BigInteger org.bouncycastle.util.BigIntegers.modOddInverse(java.math.BigInteger, java.math.BigInteger)'
[info]   at org.bouncycastle.bcpg.RSASecretBCPGKey.<init>(Unknown Source)
[info]   at org.bouncycastle.openpgp.PGPSecretKey.extractPrivateKey(Unknown Source)
[info]   at com.dwolla.security.crypto.PGPKeyAlg$$anon$1.$anonfun$readPrivateKey$2(PGPKeyAlg.scala:39)
...
```

**Comment by CJSmith-0141** [comment]
I'm pretty fuzzy on why `bcpg` doesn't bring in `bcutil`... would adding `bcutil` as a dependency over `bcprov` be ok?

**Comment by bpholt** [comment]
It looks to me like [`org.bouncycastle.util.BigIntegers`](https://github.com/bcgit/bc-java/blob/master/core/src/main/jdk1.1/org/bouncycastle/util/BigIntegers.java) is [part of `bcprov`](https://github.com/bcgit/bc-java/blob/master/prov/build.gradle#L2). (`bcutil` [shows up](https://www.bouncycastle.org/latest_releases.html) in the "ASN.1 Utility Classes" column on the Bouncy Castle releases page and doesn't appear in the dependency tree for this project, so I _think_ it's unneeded.)

If that's true, the intended version of `bcprov` is already in the dependency tree of this project, as a transitive dependency of `bcpg`. I think if a downstream app pulls in this library and also a different version of `bcprov`, then that will control—adding it here would still be a transitive dependency from the perspective of that app. If _that's_ true, then does it actually help to explicitly track the `bcprov` versions here? It feels like we'd be adding maintenance work for relatively little value. 

What do you think?

**Comment by CJSmith-0141** [comment]
I can agree with that. I'll close this PR.

**Comment by bpholt** [comment]
Thanks anyway, though! I really appreciate the feedback and the willingness to contribute.

**Comment by CJSmith-0141** [comment]
No worries! Happy to give it a shot.

**Pull request closed without merging**
